core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('syncomercial.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    url(r'^_nested_admin/', include('nested_admin.urls')),
]

syncomercial/urls.py
from django.urls import path, include

from . import views

app_name = 'syncomercial'

urlpatterns = [
    path('', views.index, name='index'),
    path('distribuidores/', views.distribuidores, name='distribuidores'),
    path('distribuidores/<int:distribuidor_id>/', views.distribuidor_detalhe, name='distribuidor_detalhe'),
    path('filial/<int:filial_id>/', views.filial_detalhe, name='filial_detalhe'),
    path('filial/editar/<int:filial_id>/', views.filial_editar, name='filial_editar'),
    path('filial/adicionar/<int:distribuidor_id>/', views.filial_adicionar, name='filial_adicionar'),
    
    
    path('rtvs/', views.rtvs, name='rtvs'),
    path('rtvs/<int:rtv_id>', views.rtv_detalhe, name='rtv_detalhe'),
    path('rtvs/editar/<int:rtv_id>', views.rtv_editar, name='rtv_editar'),
    path('rtvs/adicionar', views.rtv_adicionar, name='rtv_adicionar'),
    
    path('rtvs/atribuir/<distribuidor_id>/', views.rtv_atribuir, name='rtv_atribuir'),
    path('rtvs/desatribuir/<rtv_id>&<distribuidor_id>/', views.rtv_desatribuir, name='rtv_desatribuir'),
    
    path('responsaveis/', views.responsaveis, name='responsaveis'),
    path('responsaveis/<int:responsavel_id>', views.responsavel_detalhe, name='responsavel_detalhe'),
    path('responsaveis/editar/<int:responsavel_id>', views.responsavel_editar, name='responsavel_editar'),
    path('responsaveis/adicionar', views.responsavel_adicionar, name='responsavel_adicionar'),
    
    path('responsaveis/atribuir/<distribuidor_id>/', views.responsavel_atribuir, name='responsavel_atribuir'),
    path('responsaveis/desatribuir/<responsavel_id>&<distribuidor_id>/', views.responsavel_desatribuir, name='responsavel_desatribuir'),
]

syncomercial/forms.py
from django import forms

from .models import Filial, RTV, Responsavel, RTV_Distribuidor, Responsavel_Distribuidor

class FilialForm(forms.ModelForm):
    class Meta:
        model = Filial
        fields = [
            'distribuidor',
            'codigo',
            'nome',
            'cnpj',
            'responsavel',
            'ddd',
            'telefone',
            'endereco',
            'cidade',
            'estado',
            'codibge',
            'latitude',
            'longitude',
        ]
        

class RtvForm(forms.ModelForm):
    class Meta:
        model = RTV
        fields = [
            'nome',
            'code_spoca',
            'email',
            'ddd1',
            'telefone1',
            'ramal1',
            'ddd2',
            'telefone2',
            'ramal2',
            'anotacao',
            'status',
        ]
        
class ResponsavelForm(forms.ModelForm):
    class Meta:
        model = Responsavel
        fields = [
            'nome',
            'cargo',
            'atuacao',
            'email',
            'ddd1',
            'telefone1',
            'ramal1',
            'ddd2',
            'telefone2',
            'ramal2',
            'anotacao',
            'status',
        ]
        
        
class RTV_DistribuidorForm(forms.ModelForm):
    class Meta:
        model = RTV_Distribuidor
        fields = [
            'distribuidor',
            'RTV',
        ]
        
class Responsavel_DistribuidorForm(forms.ModelForm):
    class Meta:
        model = Responsavel_Distribuidor
        fields = [
            'distribuidor',
            'responsavel',
        ]

syncomercial/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *

@login_required
def index(request):
    return render(request, 'syncomercial/index.html')


#Views relacionadas a DISTRIBUIDORES
@login_required
def distribuidores(request):
    """Lista todos os distribuidores"""
    distribuidores = Distribuidor.objects.all().order_by('razao_social')
    context = {
        'distribuidores': distribuidores,
    }
    return render(request, 'syncomercial/distribuidores.html', context)

@login_required
def distribuidor_detalhe(request, distribuidor_id):
    """Lista os detalhes de um distribuidor especifico"""
    distribuidor = Distribuidor.objects.get(id=distribuidor_id)
    filiais = distribuidor.filial_set.order_by('cnpj')
    rtvs = RTV_Distribuidor.objects.filter(distribuidor=distribuidor_id)
    responsaveis = Responsavel_Distribuidor.objects.filter(distribuidor=distribuidor_id)
    print(len(rtvs))
    context = {
        'distribuidor': distribuidor,
        'filiais': filiais,
        'rtvs': rtvs,
        'responsaveis': responsaveis,
    }
    return render(request, 'syncomercial/distribuidor_detalhe.html', context)

@login_required
def filial_detalhe(request, filial_id):
    """Lista os detalhes de uma filial em especifico"""
    filial = Filial.objects.get(id=filial_id)
    
    context = {
        'filial': filial,
    }
    return render(request, 'syncomercial/filial_detalhe.html', context)

@login_required
def filial_editar(request, filial_id):
    """Editar os dados de uma filial em especifico"""
    filial = filial = Filial.objects.get(id=filial_id)
    
    if request.method != 'POST':
        #Requisicao inicial, preenche o formulario com os dados!
        form = FilialForm(instance=filial)
    else:
        #Requisicao com edicao: validar, processar e salvar os dados.
        form = FilialForm(instance=filial, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('syncomercial:distribuidor_detalhe', distribuidor_id=filial.distribuidor_id)
        
    context = {'filial': filial, 'form': form}
    return render(request, 'syncomercial/filial_editar.html', context)

@login_required
def filial_adicionar(request, distribuidor_id):
    """Adiciona nova filial a um distribuidor em especifico"""    
    if request.method != 'POST':
        #Formulario em Branco
        form = FilialForm(initial={'distribuidor': distribuidor_id })
        
    else:
        #Formulario preenchido
        form = FilialForm(data=request.POST)
        if form.is_valid():
            #Formulario validado
            form.save()
        return redirect('syncomercial:distribuidor_detalhe', distribuidor_id = distribuidor_id)
        
    
    context = {'form': form}
    return render(request, 'syncomercial/filial_adicionar.html', context)


#Views relacionadas a RTVS
@login_required
def rtvs(request):
    """Lista todos os distribuidores"""
    rtvs = RTV.objects.all().order_by('nome')
    context = {
        'rtvs': rtvs,
    }
    return render(request, 'syncomercial/rtvs.html', context)

@login_required
def rtv_detalhe(request, rtv_id):
    rtv = RTV.objects.get(id=rtv_id)
    context = {
        'rtv': rtv
    }
    return render(request, 'syncomercial/rtv_detalhe.html', context)

@login_required
def rtv_editar(request, rtv_id):
    """Editar os dados de um rtv em especifico"""
    rtv = RTV.objects.get(id=rtv_id)
    
    if request.method != 'POST':
        #Requisicao inicial, preenche o formulario com os dados!
        form = RtvForm(instance=rtv)
    else:
        #Requisicao com edicao: validar, processar e salvar os dados.
        form = RtvForm(instance=rtv, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('syncomercial:rtv_detalhe', rtv_id=rtv_id)
        
    context = {'rtv': rtv, 'form': form}
    return render(request, 'syncomercial/rtv_editar.html', context)

@login_required
def rtv_adicionar(request):
    """Adiciona novo RTV"""
    if request.method != 'POST':
        #Formulario em Branco
        form = RtvForm()
    else:
        #Formulario preenchido
        form = RtvForm(data=request.POST)
        if form.is_valid():
            #Formulario validado
            form.save()
        return redirect('syncomercial:rtvs')
        
    
    context = {'form': form}
    return render(request, 'syncomercial/rtv_adicionar.html', context)

@login_required
def rtv_atribuir(request, distribuidor_id):
    """Cria a relacao entre RTV e Distribuidor"""
    print(f"Distribuidor ID: {distribuidor_id}")
    
    if request.method != 'POST':
        #Formulario inicial, com os dados atuais.
        print('metodo POST')
        form = RTV_DistribuidorForm(initial={'distribuidor': distribuidor_id })
    else:
        #Formulario Preenchido
        print('metodo POST')
        form = RTV_DistribuidorForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('syncomercial:distribuidor_detalhe', distribuidor_id=distribuidor_id)
    
    context = {'form':form}
    return render(request, 'syncomercial/rtv_atribuir.html', context)


@login_required
def rtv_desatribuir(request, rtv_id, distribuidor_id):
    """Desatribuir/Deletar uma relacao entre RTV e Distribuidor"""
    relacao = RTV_Distribuidor.objects.get(RTV=rtv_id, distribuidor=distribuidor_id)
    relacao.delete()
    return redirect('syncomercial:distribuidor_detalhe', distribuidor_id=distribuidor_id)


#Views relacionadas a RESPONSAVEIS
@login_required
def responsaveis(request):
    """Lista todos os responsaveis"""
    responsaveis = Responsavel.objects.all().order_by('nome')
    context = {
        'responsaveis': responsaveis,
    }
    return render(request, 'syncomercial/responsaveis.html', context)

@login_required
def responsavel_detalhe(request, responsavel_id):
    responsavel = Responsavel.objects.get(id=responsavel_id)
    context = {
        'responsavel': responsavel
    }
    return render(request, 'syncomercial/responsavel_detalhe.html', context)

@login_required
def responsavel_editar(request, responsavel_id):
    """Editar os dados de um responsavel em especifico"""
    responsavel = Responsavel.objects.get(id=responsavel_id)
    
    if request.method != 'POST':
        #Requisicao inicial, preenche o formulario com os dados!
        form = ResponsavelForm(instance=responsavel)
    else:
        #Requisicao com edicao: validar, processar e salvar os dados.
        form = ResponsavelForm(instance=responsavel, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('syncomercial:responsavel_detalhe', responsavel_id=responsavel_id)
        
    context = {'responsavel': responsavel, 'form': form}
    return render(request, 'syncomercial/responsavel_editar.html', context)

@login_required
def responsavel_adicionar(request):
    
    """Adiciona novo Responsavel"""
    if request.method != 'POST':
        #Formulario em Branco
        form = ResponsavelForm()
    else:
        #Formulario preenchido
        form = ResponsavelForm(data=request.POST)
        if form.is_valid():
            #Formulario validado
            form.save()
        return redirect('syncomercial:responsaveis')
        
    
    context = {'form': form}
    return render(request, 'syncomercial/responsavel_adicionar.html', context)

@login_required
def responsavel_atribuir(request, distribuidor_id):
    """Cria a relacao entre Responsavel e Distribuidor"""
    print(f"Distribuidor ID: {distribuidor_id}")
    
    if request.method != 'POST':
        #Formulario inicial, com os dados atuais.
        print('metodo POST')
        form = Responsavel_DistribuidorForm(initial={'distribuidor': distribuidor_id })
    else:
        #Formulario Preenchido
        print('metodo POST')
        form = Responsavel_DistribuidorForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('syncomercial:distribuidor_detalhe', distribuidor_id=distribuidor_id)
    
    context = {'form':form}
    return render(request, 'syncomercial/responsavel_atribuir.html', context)

@login_required
def responsavel_desatribuir(request, responsavel_id, distribuidor_id):
    """Desatribuir/Deletar uma relacao entre Responsavel e Distribuidor"""
    relacao = Responsavel_Distribuidor.objects.get(responsavel=responsavel_id, distribuidor=distribuidor_id)
    relacao.delete()
    return redirect('syncomercial:distribuidor_detalhe', distribuidor_id=distribuidor_id)

syncomercial/templates/syncomercial/distribuidor_detalhe.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}DETALHES DO DISTRIBUIDOR{% endblock %}

{% block content %}
<!-- Card com Dados Basicos -->
<div class="card card-info" style="max-width: 1024px;">
  <div class="card-header bg-secondary">
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
    </div>
    <h3 class="card-title">Dados B&aacute;sicos</h3>
  </div>
  <div class="card-body">
    <div class="form-group row">
      <label for="id" class="col-sm-2 col-form-label">ID</label>
      <div class="col-sm-4">
        <input class="form-control-plaintext border-bottom border-top-0 border-gray" id="code_sap" placeholder="{{ distribuidor.id }}" readonly>
      </div>
      <div class="col-sm-6 mt-auto">
        <small class="form-text text-muted">* identifica&ccedil;&atilde;o do distribuidor no sistema Onix Web</small>
      </div>
    </div>
    <div class="form-group row">
      <label for="code_sap" class="col-sm-2 col-form-label">Code SAP</label>
      <div class="col-sm-4">
        <input class="form-control-plaintext border-bottom border-top-0 border-gray" id="code_sap" placeholder="{{ distribuidor.code_sap }}" readonly>
      </div>
      <div class="col-sm-6 mt-auto">
        <small class="form-text text-muted">* identifica&ccedil;&atilde;o do distribuidor na Syngenta</small>
      </div>
    </div>
    <div class="form-group row">
      <label for="razao_social" class="col-sm-2 col-form-label">Raz&atilde;o Social</label>
      <div class="col-sm-10">
        <input class="form-control-plaintext border-bottom border-top-0 border-gray" id="razao_social" placeholder="{{ distribuidor.razao_social }}" readonly>
      </div>
    </div>
    <div class="form-group row">
      <label for="nome_fantasia" class="col-sm-2 col-form-label">Nome Fantasia</label>
      <div class="col-sm-10">
        <input class="form-control-plaintext border-bottom border-top-0 border-gray" id="razao_social" placeholder="{{ distribuidor.nome_fantasia }}" readonly>
      </div>
    </div>
  </div>  
</div>
<!-- Card com Dados Basicos -->

<!-- Card com dados das RTVS --> 
<div class="card card-info" style="max-width: 1024px;">
  <div class="card-header bg-secondary">
    <div class="container-fluid ">
      <div class="row">
        <div>
          <h3 class="card-title">RTVs</h3>
        </div>
        <div class="ml-auto">
          <a href="{% url 'syncomercial:rtv_atribuir' distribuidor.id %}" type="button" class="btn btn-block btn-success btn-xs ml-auto"><i class="fas fa-sign-in-alt"></i> Atribuir</a>
        </div>
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0">
      <table class="table table-hover table-striped" data-link="row">
        {% if rtvs %}
        <thead class="bg-secondary">
          <tr>  
            <th></th>
            <th>NOME</th>
            <th>EMAIL</th>
            <th>TELEFONES</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        {% endif %}
        <tbody>
          {% for rtv in rtvs %}
          <tr>
            <td><a class="text-warning" href="{% url 'syncomercial:rtv_editar' rtv.RTV.id %}"><i class="fas fa-edit"></i></a></td>
            <td><a href="{% url 'syncomercial:rtv_detalhe' rtv.RTV.id %}">{{ rtv.RTV.nome }}</a></td>
            <td><a href="{% url 'syncomercial:rtv_detalhe' rtv.RTV.id %}">{%if rtv.RTV.email %}{{ rtv.RTV.email }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:rtv_detalhe' rtv.RTV.id %}">{%if rtv.RTV.telefone1 %}({{ rtv.RTV.ddd1 }}) {{rtv.RTV.telefone1|slice:"-9:-4"}}-{{rtv.RTV.telefone1|slice:"-4:"}}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:rtv_detalhe' rtv.RTV.id %}">{%if rtv.RTV.telefone2 %}({{ rtv.RTV.ddd2 }}) {{rtv.RTV.telefone2|slice:"-9:-4"}}-{{rtv.RTV.telefone2|slice:"-4:"}}{% endif %}</a></td>
            <td><a class="text-danger" href="{% url 'syncomercial:rtv_desatribuir' rtv.RTV.id distribuidor.id %}"><i class="fas fa-sign-out-alt"></i></a></td>
          </tr>
          {% empty %}
          {% endfor %}
        </tbody>
      </table>
  </div>
</div>
<!-- Card com dados dos RTVs --> 

<!-- Card com dados das Responsaveis --> 
<div class="card card-info" style="max-width: 1024px;">
  <div class="card-header bg-secondary">
    <div class="container-fluid ">
      <div class="row">
        <div>
          <h3 class="card-title">Respons&aacute;veis</h3>
        </div>
        <div class="ml-auto">
          <a href="{% url 'syncomercial:responsavel_atribuir' distribuidor.id %}" type="button" class="btn btn-block btn-success btn-xs ml-auto"><i class="fas fa-sign-in-alt"></i> Atribuir</a>
        </div>
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0">
      <table class="table table-hover table-striped" data-link="row">
        {% if responsaveis %}
        <thead class="bg-secondary">
          <tr>  
            <th></th>
            <th>Nome</th>
            <th>Atua&ccedil;&atilde;o</th>
            <th>Cargo</th>
            <th>Email</th>
            <th>Telefones</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        {% endif %}
        <tbody>
          {% for responsavel in responsaveis %}
          <tr>
            <td><a class="text-warning" href="{% url 'syncomercial:responsavel_editar' responsavel.responsavel.id %}"><i class="fas fa-edit"></i></a></td>
            <td><a href="{% url 'syncomercial:responsavel_detalhe' responsavel.responsavel.id %}">{{ responsavel.responsavel.nome }}</a></td>
            <td><a href="{% url 'syncomercial:responsavel_detalhe' responsavel.responsavel.id %}">{% if responsavel.responsavel.atuacao %}{{ responsavel.responsavel.atuacao }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:responsavel_detalhe' responsavel.responsavel.id %}">{% if responsavel.responsavel.cargo %}{{ responsavel.responsavel.cargo }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:responsavel_detalhe' responsavel.responsavel.id %}">{% if responsavel.responsavel.email %}{{ responsavel.responsavel.email }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:responsavel_detalhe' responsavel.responsavel.id %}">{% if responsavel.responsavel.telefone1 %}({{ responsavel.responsavel.ddd1 }}) {{responsavel.responsavel.telefone1|slice:"-9:-4"}}-{{responsavel.responsavel.telefone1|slice:"-4:"}}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:responsavel_detalhe' responsavel.responsavel.id %}">{% if responsavel.responsavel.telefone2 %}({{ responsavel.responsavel.ddd2 }}) {{responsavel.responsavel.telefone2|slice:"-9:-4"}}-{{responsavel.responsavel.telefone2|slice:"-4:"}}{% endif %}</a></td>
            <td><a class="text-danger" href="{% url 'syncomercial:responsavel_desatribuir' responsavel.responsavel.id distribuidor.id %}"><i class="fas fa-sign-out-alt"></i></a></td>
          </tr>
          {% empty %}
          {% endfor %}
        </tbody>
      </table>
  </div>
</div>
<!-- Card com dados dos RTVs --> 


<!-- Card com dados das Filiais --> 
<div class="card card-info" style="max-width: 1024px;">
  <div class="card-header bg-secondary">
    <div class="container-fluid ">
      <div class="row">
        <div>
          <h3 class="card-title">Filiais</h3>
        </div>
        <div class="ml-auto">
          <a href="{% url 'syncomercial:filial_adicionar' distribuidor.id %}" type="button" class="btn btn-block btn-success btn-xs ml-auto"><i class="fas fa-plus-square"></i> Adicionar</a>
        </div>
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0">
      <table class="table table-hover table-striped" data-link="row">
        {% if filiais %}
        <thead class="bg-secondary">
          <tr>
            <th></th>
            <th>Codigo</th>
            <th>Nome</th>
            <th>CNPJ</th>
            <th>Endere&ccedil;o</th>
            <th>Cidade</th>
            <th>UF</th>
          </tr>
        </thead>
        {% endif %}
        <tbody>
          {% for filial in filiais %}
          <tr>
            <td><a class="text-warning" href="{% url 'syncomercial:filial_editar' filial.id %}"><i class="fas fa-edit"></i></a></td>
            <td><a href="{% url 'syncomercial:filial_detalhe' filial.id %}">{% if filial.codigo %}{{ filial.codigo }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:filial_detalhe' filial.id %}">{% if filial.nome %}{{ filial.nome }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:filial_detalhe' filial.id %}">{% if filial.cnpj %}{{ filial.cnpj|slice:":2" }}.{{ filial.cnpj|slice:"2:5" }}.{{ filial.cnpj|slice:"5:8" }}/{{ filial.cnpj|slice:"8:12" }}-{{ filial.cnpj|slice:"12:14" }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:filial_detalhe' filial.id %}">{% if filial.endereco %}{{ filial.endereco|truncatechars:40 }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:filial_detalhe' filial.id %}">{% if filial.cidade %}{{ filial.cidade }}{% endif %}</a></td>
            <td><a href="{% url 'syncomercial:filial_detalhe' filial.id %}">{% if filial.estado %}{{ filial.estado }}{% endif %}</a></td>
          </tr>
          {% empty %}
          {% endfor %}
        </tbody>
      </table>
  </div>
</div>
<!-- Card com dados das Filiais --> 




{% endblock content %}

syncomercial/templates/syncomercial/filial_adicionar.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}ADICIONAR FILIAL{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:filial_adicionar' form.distribuidor.value %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">ADICIONAR</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/filial_editar.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}EDITAR FILIAL{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:filial_editar' filial.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Save Changes</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/index.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}{% endblock %}

{% block content %}

{% endblock %}

syncomercial/templates/syncomercial/responsavel_adicionar.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}ADICIONAR RESPONS&Aacute;VEL{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:responsavel_adicionar' %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">ADICIONAR</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/responsavel_atribuir.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}ATRIBUIR RESPONS&Aacute;VEL{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:responsavel_atribuir' form.distribuidor.value %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Atribuir</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/responsavel_editar.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}EDITAR RESPONS&Aacute;VEL{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:responsavel_editar' responsavel.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Save Changes</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/rtv_adicionar.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}ADICIONAR RTV{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:rtv_adicionar' %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">ADICIONAR</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/rtv_atribuir.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}ATRIBUIR RTV{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:rtv_atribuir' form.distribuidor.value %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Atribuir</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/rtv_editar.html
{% extends 'syncomercial/base.html' %}


{% block page_name %}EDITAR RTV{% endblock %}

{% block content %}
    <!-- Form com Dados Basicos -->
    <div class="card card-info" style="max-width: 1024px;">
        <form action="{% url 'syncomercial:rtv_editar' rtv.id %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit">Save Changes</button>
        </form>
    </div>

      <!-- /.card -->
{% endblock content %}

syncomercial/templates/syncomercial/teste.html
<div class="box box-warning">
    <div class="box-header with-border">
        <h3 class="box-title">Collapsable</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
        <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body" style="">
        The body of the box
    </div>
    <!-- /.box-body -->
</div>